services:
  mongodb:
    image: mongo:6
    container_name: fittrack-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fittrack
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: fittrack-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fittrack-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    build: ./api-service
    container_name: fittrack-api-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./api-service/.env

  worker-service:
    build: ./worker-service
    container_name: fittrack-worker-service
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      api-service:
        condition: service_started
    env_file:
      - ./worker-service/.env

  python-service:
    build: ./python-service
    container_name: fittrack-python-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./python-service/.env

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data: